apiVersion: v1
kind: Service
metadata:
  name: workload-simulator
  namespace: default
  labels:
    app: workload-simulator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app: workload-simulator
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
